version: '3.1'

services:
  my-postgres:
    image: postgres:16.1-alpine3.19
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: simple_bank
    ports:
      - "5432:5432"

  redis:
    image: redis:7.2.4-alpine3.19
    restart: always
    ports:
      - "6379:6379"