name: Deploy to production

on:
  # 練習僅限手動觸發
  workflow_dispatch:

jobs:

  build:
    name: Build image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
      # https://repost.aws/zh-Hant/knowledge-center/secondary-account-access-ecr
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-session-name: GithubActionsSimpleBankDeploy
        role-to-assume: arn:aws:iam::905418378273:role/aws-service-role/replication.ecr.amazonaws.com/AWSServiceRoleForECRReplication
        aws-region: ap-northeast-3

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      with:
        mask-password: true

    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: simplebank
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
